# Generated by Django 5.0.2 on 2024-02-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Persona_asignada', models.CharField(max_length=20)),
                ('Titulo', models.CharField(max_length=40)),
                ('Descripcion', models.TextField(blank=True)),
                ('Estado', models.BooleanField(default=False)),
                ('Archivo', models.FileField(upload_to='upload/')),
            ],
        ),
    ]

